config/routes.rb
MATHunter::Application.routes.draw do
  root :to => 'tutorials#highlights'
  
  resources :tutorials do
    resources :chapters
  end
  
  resources :chapters do 
    resources :comments
  end
  
  resources :user_sessions
  resources :users
  
  get 'about' => 'pages#about', :as => :about
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  
  get 'voteGood/:id' => 'tutorials#voteGood', :as => :voteGood
  get 'voteBad/:id' => 'tutorials#voteBad', :as => :voteBad
  
  mathjax 'mathjax'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  
  validates :email, uniqueness: true, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to(:root, alert: 'Access denied !')
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if checkCredentials
      redirect_to(:users, alert: 'Access denied !')
    else
      # get tutorials for the current user logged
      @tutorials = Tutorial.where(:user_id => @user.id)
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    # respond_to do |format|
      # if @user.save
        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @user }
      # else
        # format.html { render action: 'new' }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      # end
    # end
    if @user.save
        redirect_to(:root, alert: 'User was successfully created')
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to :root, alert: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        @tutorials = Tutorial.where(:user_id => @user.id)
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if checkCredentials
      redirect_to(:users, alert: 'Access denied !')
    else
      @user.destroy
      respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if checkIfUserExists
        @user = User.find(params[:id])
      else
        redirect_to(:users)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
    
    def checkCredentials
      if current_user.id != @user.id
        return true
      else
        return false
      end
    end
    
    def checkIfUserExists
      if User.where(:id => params[:id]).empty?
        return false
      else
        return true
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>New User</h1>

<div class="text-center">
<%= render 'form' %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<table class="user_edit">
	<tr>
		<td>
			<h2>Your account</h2>
			<%= render 'form' %>
		</td>
		<td>
			<h2>Your tutorials</h2>
			<% if not @tutorials.empty? %>
			
				<% @tutorials.each do |tutorial| %>
					<div><%= link_to tutorial.title, tutorial_path(tutorial) %></div>
				<% end %>
			
			<% else %>
			<p>
				Presently you don't have any tutorial.  <br />
				<%= link_to 'Create your first !', new_tutorial_path %>
			</p>
			<% end %>
		</td>
	</tr>
</table>

app/views/users/index.html.erb
<h3>Users List</h3>

app/views/users/new.html.erb
<h1>Sign up</h1>

<table class="user_edit">
	<tr>
		<td>
			<h2>Account</h2>
			<%= render 'form' %>
		</td>
		<td>
			<h2>About registration</h2>
			<p><strong>Create an account to :</strong></p>
			Create tutorials about mathematics.<br />
			Add comments to chapter from all tutorials.<br />
			Participate in the community by voting for tutorials.
		</td>
	</tr>
</table>

app/views/users/show.html.erb
<p>Access denied</p>
<%= link_to 'Back', edit_user_path(@user) %>