config/routes.rb
MATHunter::Application.routes.draw do
  root :to => 'tutorials#highlights'
  
  resources :tutorials do
    resources :chapters
  end
  
  resources :chapters do 
    resources :comments
  end
  
  resources :user_sessions
  resources :users
  
  get 'about' => 'pages#about', :as => :about
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  
  get 'voteGood/:id' => 'tutorials#voteGood', :as => :voteGood
  get 'voteBad/:id' => 'tutorials#voteBad', :as => :voteBad
  
  mathjax 'mathjax'

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :tutorial
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_filter :require_login, :except => [:index, :show]
  
  def index
    @tutorial = get_related_tutorial
    
    case @tutorial.difficulty
    when 1
      @stringDifficulty = "Easy"
    when 2
      @stringDifficulty = "Medium"
    else
      @stringDifficulty = "Hard"
    end
    
    @chapters = @tutorial.chapters.paginate(:page => params[:page], :per_page => 10)
  end
  
  def show
    @tutorial = get_related_tutorial
    @chapter = Chapter.find(params[:id])
    @chapters = @tutorial.chapters
    
    @comments = @chapter.comments.paginate(page: params[:page])
    @comment = Comment.new 
  end
  
  def new
    @tutorial = get_related_tutorial
    if @tutorial.user_id != current_user.id
      redirect_to(:tutorials, alert: 'Access Denied !')
    else
      @chapter = Chapter.new
    end
  end
  
  def edit
    @tutorial = get_related_tutorial
    @chapter = Chapter.find(params[:id])
    
    if @tutorial.user_id != current_user.id
      redirect_to(:tutorials, alert: 'Access Denied !')
    end
  end
  
  def create
    @tutorial = get_related_tutorial
    @chapter = Chapter.new(get_params)
    @chapter.tutorial_id = @tutorial.id
    
    if @chapter.save
      redirect_to tutorial_chapter_path(@tutorial, @chapter)
    else
      render 'new'
    end
  end
  
  def update
    @tutorial = get_related_tutorial
    @chapter = Chapter.find(params[:id])
    
    if @chapter.update(get_params)
      redirect_to tutorial_chapter_path(@tutorial, @chapter)
    else
      render 'edit'
    end
  end
  
  def destroy
    @tutorial = get_related_tutorial
    @chapter = Chapter.find(params[:id])
    
    if @tutorial.user_id != current_user.id
      redirect_to(:tutorials, :alert => 'Acess denied !')
    else
      @chapter.destroy
      redirect_to tutorial_chapters_path(@tutorial)
    end
  end
  
  private
  
  def get_params
    params[:chapter].permit(:title, :content)
  end
  
  def get_related_tutorial
    Tutorial.find(params[:tutorial_id])
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<div id="chapter_form">

<%= form_for [@tutorial, @chapter] do |f| %>
	<div class="field title">
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :content %><br />
		<%= f.text_area :content, :class => 'ckeditor' %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

</div>

app/views/chapters/edit.html.erb
<h1><%= @tutorial.title %></h1>
<h2>Edit chapter</h2>
<%= render 'form' %>

app/views/chapters/index.html.erb
<div class="top-right">
	<%= link_to image_tag('/images/icons/back.png') + 'Back to tutorial list', tutorials_path, { :class => "actionlink" } %>
	<%= link_to image_tag('/images/icons/add.png') + 'New chapter', new_tutorial_chapter_path, { :class => "actionlink" } %>
	<%= link_to image_tag('/images/icons/edit.png') + 'Edit', edit_tutorial_path(@tutorial), { :class => "actionlink" } %>
	<%= link_to image_tag('/images/icons/delete.png') + 'Delete', tutorial_path(@tutorial), { :method => 'delete', :class => "actionlink" } %>
</div>
<h1><%= @tutorial.title %></h1>
<% if not @tutorial.image.blank? %>
<img class="tutorial_image" src="<%= root_url + @tutorial.image %>" alt="<%= @tutorial.title %>" /> 
<% end %>
<p>
	Difficulty : <%= @stringDifficulty %>
</p>
<p>
	<%= @tutorial.description %>
</p>
<p>
	<%= link_to '+1', voteGood_path(@tutorial) %> | 
	<%= link_to '-1', voteBad_path(@tutorial) %> 
	(Current Score: <%= @tutorial.score %>)
</p>
<table cellspacing="10">
	<% @chapters.each_with_index do |chapter, index| %>
	<tr>
		<td class="chapter"><%= index + 1 %></td>
		<td><h2><%= link_to chapter.title, tutorial_chapter_path(@tutorial, chapter) %></h2></td>
	</tr>
	<% end %>
</table>
<%= will_paginate @chapters %>

app/views/chapters/new.html.erb
<h1><%= @tutorial.title %></h1>
<h2>New chapter</h2>
<%= render 'form' %>

app/views/chapters/show.html.erb
<div class="top-right">
	<%= link_to image_tag('/images/icons/back.png') + 'Back to tutorial', tutorial_chapters_path(@tutorial), { :class => "actionlink" } %>
</div>

<h1><%= @tutorial.title %></h1>

<div id="tutorial">
	<div class="tab">
		<ul>
			<% @chapters.each do |chapter| %>
				<li <% if chapter.id == @chapter.id %>class="selected"<% end %>>
					<%= link_to chapter.title, tutorial_chapter_path(@tutorial, chapter) %>
				</li>
			<% end %>
		</ul>
	</div>
	<div class="content">
		<div class="top-right">
			<%= link_to image_tag('/images/icons/edit.png') + 'Edit', edit_tutorial_chapter_path(@tutorial, @chapter), { :class => "actionlink" } %>
			<%= link_to image_tag('/images/icons/delete.png') + 'Delete', tutorial_chapter_path(@tutorial, @chapter), { :method => 'delete', :class => "actionlink" } %>
		</div>
		<h2><%= @chapter.title %></h2>
		<p>
			<%= @chapter.content.html_safe %>
		</p>
	</div>
</div>

<h2>Comments</h2>
<table class="comment_list">
	<%= render @comments %>
</table>
<%= will_paginate @comments %>
<%= render 'comments/form' %>